stream_options:
  - exchange: "binance"
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "ADAUSDT"
    dataTypes:
      - "quote"
  - exchange: "binance-futures"
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "ADAUSDT"
    dataTypes:
      - "quote"

redis_options:
  redis_tick_cache:
    redis_expiry: 600
  sampled_data_manager:
    redis_expiry: 100
    redis_max_len: 100

disk_writer_options:
  flush_interval: 10

kafka_options:
  kafka_broker: "localhost:9092"

recording_options:
  recorder_consumer_dir: '/media/cong1989/Expansion1/work_for_autonomous/crypto_tick_data'
  precise_sampler_dir: '/media/cong1989/Expansion1/work_for_autonomous/crypto_data_sample'

sampled_data_manager_options:
  max_tick_age: 100